name: Project Tests
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.12.4 
      - name: Install dependencies
        run: |
          python -m pip install -upgrade pip
          pip install -r requirments.txt
      - name: Test with pytest
        run: pytest
